package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/hpcloud/cf-usb/lib/broker/operations/catalog"
)

// NewBrokerAPI creates a new Broker instance
func NewBrokerAPI(spec *loads.Document) *BrokerAPI {
	o := &BrokerAPI{
		spec:            spec,
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
	}

	return o
}

/*BrokerAPI The Cloud Foundry services API defines the contract between the Cloud Controller and the service broker. The broker is expected to implement several HTTP (or HTTPS) endpoints underneath a URI prefix. One or more services can be provided by a single broker, and load balancing enables horizontal scalability of redundant brokers. Multiple Cloud Foundry instances can be supported by a single broker using different URL prefixes and credentials. [Learn more about the Service Broker API.](http://docs.cloudfoundry.org/services/api.html) */
type BrokerAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// BasicAuth registers a function that takes username and password and returns a principal
	// it performs authentication with basic auth
	BasicAuth func(string, string) (interface{}, error)

	// GetServiceInstancesInstanceIDLastOperationHandler sets the operation handler for the get service instances instance ID last operation operation
	GetServiceInstancesInstanceIDLastOperationHandler GetServiceInstancesInstanceIDLastOperationHandler
	// CatalogCatalogHandler sets the operation handler for the catalog operation
	CatalogCatalogHandler catalog.CatalogHandler
	// CreateServiceInstanceHandler sets the operation handler for the create service instance operation
	CreateServiceInstanceHandler CreateServiceInstanceHandler
	// DeprovisionServiceInstanceHandler sets the operation handler for the deprovision service instance operation
	DeprovisionServiceInstanceHandler DeprovisionServiceInstanceHandler
	// ServiceBindHandler sets the operation handler for the service bind operation
	ServiceBindHandler ServiceBindHandler
	// ServiceUnbindHandler sets the operation handler for the service unbind operation
	ServiceUnbindHandler ServiceUnbindHandler
	// UpdateServiceInstanceHandler sets the operation handler for the update service instance operation
	UpdateServiceInstanceHandler UpdateServiceInstanceHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *BrokerAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *BrokerAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// DefaultProduces returns the default produces media type
func (o *BrokerAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *BrokerAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *BrokerAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *BrokerAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the BrokerAPI
func (o *BrokerAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BasicAuth == nil {
		unregistered = append(unregistered, "BasicAuth")
	}

	if o.GetServiceInstancesInstanceIDLastOperationHandler == nil {
		unregistered = append(unregistered, "GetServiceInstancesInstanceIDLastOperationHandler")
	}

	if o.CatalogCatalogHandler == nil {
		unregistered = append(unregistered, "catalog.CatalogHandler")
	}

	if o.CreateServiceInstanceHandler == nil {
		unregistered = append(unregistered, "CreateServiceInstanceHandler")
	}

	if o.DeprovisionServiceInstanceHandler == nil {
		unregistered = append(unregistered, "DeprovisionServiceInstanceHandler")
	}

	if o.ServiceBindHandler == nil {
		unregistered = append(unregistered, "ServiceBindHandler")
	}

	if o.ServiceUnbindHandler == nil {
		unregistered = append(unregistered, "ServiceUnbindHandler")
	}

	if o.UpdateServiceInstanceHandler == nil {
		unregistered = append(unregistered, "UpdateServiceInstanceHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *BrokerAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *BrokerAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name, scheme := range schemes {
		switch name {

		case "Basic":
			_ = scheme
			result[name] = security.BasicAuth(o.BasicAuth)

		}
	}
	return result

}

// ConsumersFor gets the consumers for the specified media types
func (o *BrokerAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *BrokerAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *BrokerAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

func (o *BrokerAPI) initHandlerCache() {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/service_instances/{instance_id}/last_operation"] = NewGetServiceInstancesInstanceIDLastOperation(o.context, o.GetServiceInstancesInstanceIDLastOperationHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/catalog"] = catalog.NewCatalog(o.context, o.CatalogCatalogHandler)

	if o.handlers["PUT"] == nil {
		o.handlers[strings.ToUpper("PUT")] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/service_instances/{instance_id}"] = NewCreateServiceInstance(o.context, o.CreateServiceInstanceHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/service_instances/{instance_id}"] = NewDeprovisionServiceInstance(o.context, o.DeprovisionServiceInstanceHandler)

	if o.handlers["PUT"] == nil {
		o.handlers[strings.ToUpper("PUT")] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/service_instances/{instance_id}/service_bindings/{binding_id}"] = NewServiceBind(o.context, o.ServiceBindHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/service_instances/{instance_id}/service_bindings/{binding_id}"] = NewServiceUnbind(o.context, o.ServiceUnbindHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers[strings.ToUpper("PATCH")] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/service_instances/{instance_id}"] = NewUpdateServiceInstance(o.context, o.UpdateServiceInstanceHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *BrokerAPI) Serve(builder middleware.Builder) http.Handler {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}

	return o.context.APIHandler(builder)
}
