package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/brokermodel"
)

/*GetServiceInstancesInstanceIDLastOperationOK Valid state values are 'in progress', 'succeeded', and 'failed'

swagger:response getServiceInstancesInstanceIdLastOperationOK
*/
type GetServiceInstancesInstanceIDLastOperationOK struct {

	// In: body
	Payload *brokermodel.LastOperation `json:"body,omitempty"`
}

// NewGetServiceInstancesInstanceIDLastOperationOK creates GetServiceInstancesInstanceIDLastOperationOK with default headers values
func NewGetServiceInstancesInstanceIDLastOperationOK() *GetServiceInstancesInstanceIDLastOperationOK {
	return &GetServiceInstancesInstanceIDLastOperationOK{}
}

// WithPayload adds the payload to the get service instances instance Id last operation o k response
func (o *GetServiceInstancesInstanceIDLastOperationOK) WithPayload(payload *brokermodel.LastOperation) *GetServiceInstancesInstanceIDLastOperationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service instances instance Id last operation o k response
func (o *GetServiceInstancesInstanceIDLastOperationOK) SetPayload(payload *brokermodel.LastOperation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceInstancesInstanceIDLastOperationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetServiceInstancesInstanceIDLastOperationGone Appropriate only for asynchronous delete requests. Cloud Foundry will consider this response a success and remove the resource from its database.

swagger:response getServiceInstancesInstanceIdLastOperationGone
*/
type GetServiceInstancesInstanceIDLastOperationGone struct {

	// In: body
	Payload brokermodel.Empty `json:"body,omitempty"`
}

// NewGetServiceInstancesInstanceIDLastOperationGone creates GetServiceInstancesInstanceIDLastOperationGone with default headers values
func NewGetServiceInstancesInstanceIDLastOperationGone() *GetServiceInstancesInstanceIDLastOperationGone {
	return &GetServiceInstancesInstanceIDLastOperationGone{}
}

// WithPayload adds the payload to the get service instances instance Id last operation gone response
func (o *GetServiceInstancesInstanceIDLastOperationGone) WithPayload(payload brokermodel.Empty) *GetServiceInstancesInstanceIDLastOperationGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service instances instance Id last operation gone response
func (o *GetServiceInstancesInstanceIDLastOperationGone) SetPayload(payload brokermodel.Empty) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceInstancesInstanceIDLastOperationGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
