package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/brokermodel"
)

/*CatalogOK successful operation

swagger:response catalogOK
*/
type CatalogOK struct {

	// In: body
	Payload *brokermodel.CatalogServices `json:"body,omitempty"`
}

// NewCatalogOK creates CatalogOK with default headers values
func NewCatalogOK() *CatalogOK {
	return &CatalogOK{}
}

// WithPayload adds the payload to the catalog o k response
func (o *CatalogOK) WithPayload(payload *brokermodel.CatalogServices) *CatalogOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the catalog o k response
func (o *CatalogOK) SetPayload(payload *brokermodel.CatalogServices) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CatalogOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
