package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CatalogHandlerFunc turns a function with the right signature into a catalog handler
type CatalogHandlerFunc func(interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CatalogHandlerFunc) Handle(principal interface{}) middleware.Responder {
	return fn(principal)
}

// CatalogHandler interface for that can handle valid catalog params
type CatalogHandler interface {
	Handle(interface{}) middleware.Responder
}

// NewCatalog creates a new http.Handler for the catalog operation
func NewCatalog(ctx *middleware.Context, handler CatalogHandler) *Catalog {
	return &Catalog{Context: ctx, Handler: handler}
}

/*Catalog swagger:route GET /catalog catalog catalog

Gets services registered within the broker

The first endpoint that a broker must implement is the service catalog. Cloud Controller will initially fetch this endpoint from all brokers and make adjustments to the user-facing service catalog stored in the Cloud Controller database.

*/
type Catalog struct {
	Context *middleware.Context
	Handler CatalogHandler
}

func (o *Catalog) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
