package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/SUSE/cf-usb/lib/csm/models"
)

// DeleteWorkspaceReader is a Reader for the DeleteWorkspace structure.
type DeleteWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteWorkspaceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteWorkspaceOK creates a DeleteWorkspaceOK with default headers values
func NewDeleteWorkspaceOK() *DeleteWorkspaceOK {
	return &DeleteWorkspaceOK{}
}

/*DeleteWorkspaceOK handles this case with default header values.

delete workspace
*/
type DeleteWorkspaceOK struct {
}

func (o *DeleteWorkspaceOK) Error() string {
	return fmt.Sprintf("[DELETE /workspaces/{workspace_id}][%d] deleteWorkspaceOK ", 200)
}

func (o *DeleteWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteWorkspaceDefault creates a DeleteWorkspaceDefault with default headers values
func NewDeleteWorkspaceDefault(code int) *DeleteWorkspaceDefault {
	return &DeleteWorkspaceDefault{
		_statusCode: code,
	}
}

/*DeleteWorkspaceDefault handles this case with default header values.

generic error response
*/
type DeleteWorkspaceDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete workspace default response
func (o *DeleteWorkspaceDefault) Code() int {
	return o._statusCode
}

func (o *DeleteWorkspaceDefault) Error() string {
	return fmt.Sprintf("[DELETE /workspaces/{workspace_id}][%d] deleteWorkspace default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteWorkspaceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
