---
packages:
- name: cf-usb
  version: !binary |-
    MTBlNTA1ZmMzOTNkYjEzMjFhMzY3NzJiNTg0Nzg1NWZlNDBmNDc3Yw==
  fingerprint: !binary |-
    MTBlNTA1ZmMzOTNkYjEzMjFhMzY3NzJiNTg0Nzg1NWZlNDBmNDc3Yw==
  sha1: !binary |-
    MzExNjc5Y2Y3M2M3ZWU1ZWEwMDkwOWJiZmU4YzUzMTRkMTA0ZDViMQ==
  dependencies: []
jobs:
- name: cf-usb
  version: !binary |-
    ODI4YWNiM2ZjMmY2YWZiY2FlYjQwYTk5Nzg0NDJhOWM0Y2E4NjFmOQ==
  fingerprint: !binary |-
    ODI4YWNiM2ZjMmY2YWZiY2FlYjQwYTk5Nzg0NDJhOWM0Y2E4NjFmOQ==
  sha1: !binary |-
    Y2MyM2Q4YjFjMjM4YmEzZTlkOTg0ZmUyY2ZiMzJmNDExNzQzZWUwZg==
commit_hash: '00000000'
uncommitted_changes: false
name: cf-usb-release
version: 0+dev.19
