---
packages:
- name: cf-usb
  version: !binary |-
    YzI3YzVhMTY3NjBjYjA2Y2EzMTgyNTAxMDE1MTRiYzVmMTVhNjk2Ng==
  fingerprint: !binary |-
    YzI3YzVhMTY3NjBjYjA2Y2EzMTgyNTAxMDE1MTRiYzVmMTVhNjk2Ng==
  sha1: !binary |-
    MzBmYzZlY2Y3MWMxNzUxOGQxNjA5YWM1NjQ3ZDIxMDkxY2RlY2E4Mw==
  dependencies: []
jobs:
- name: cf-usb
  version: !binary |-
    MmNkNGExYTA5YzZkMjk3NmRhMWIyODI3ZTgyNGMyODdkMzEwMTQ1MQ==
  fingerprint: !binary |-
    MmNkNGExYTA5YzZkMjk3NmRhMWIyODI3ZTgyNGMyODdkMzEwMTQ1MQ==
  sha1: !binary |-
    ZmM2YWFjMWY2ZDU3YmI2YzI5ZjA4MDAzNWEwMzZmYTc2M2JhYTg4OQ==
commit_hash: '00000000'
uncommitted_changes: false
name: cf-usb-release
version: 0+dev.9
