---
packages:
- name: cf-usb
  version: !binary |-
    NDQ0MWQyOTYyNzYyYjdiN2M0MTJkMTM1YjhkMGU0MTI1YmI3ODkyNw==
  fingerprint: !binary |-
    NDQ0MWQyOTYyNzYyYjdiN2M0MTJkMTM1YjhkMGU0MTI1YmI3ODkyNw==
  sha1: !binary |-
    NzQzZmE3MzE4NmQ5ODJlMDczMjdjZGIzYjZmODIwZWQ4ZmUzNjUyOA==
  dependencies:
  - golang_1.4
- name: golang_1.4
  version: !binary |-
    NzE0Njk4YmMzNTJkMmExZGJlMzIxMzc2ZjA2NzYwMzc1NjgxNDdiYg==
  fingerprint: !binary |-
    NzE0Njk4YmMzNTJkMmExZGJlMzIxMzc2ZjA2NzYwMzc1NjgxNDdiYg==
  sha1: !binary |-
    MDY2MTIyMDdlZmVmY2U2NDFhMjNjOWNhMjJmYzZhY2VlYzBhODZiNQ==
  dependencies: []
jobs:
- name: cf-usb
  version: !binary |-
    OTgzMTk1MWZjOGY4N2IyOTgwOTRiM2IxMjg2NzQ3MWFiNWEzNzk0Mg==
  fingerprint: !binary |-
    OTgzMTk1MWZjOGY4N2IyOTgwOTRiM2IxMjg2NzQ3MWFiNWEzNzk0Mg==
  sha1: !binary |-
    NWRhNWRmNjQxYTE4MzRjNGY3Nzc5MDk5NzVkYWUyMjI5ZjQ3YWE0NA==
commit_hash: '00000000'
uncommitted_changes: false
name: cf-usb-release
version: 0+dev.49
