package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/SUSE/cf-usb/lib/genmodel"
)

/*GetDriverEndpointOK OK

swagger:response getDriverEndpointOK
*/
type GetDriverEndpointOK struct {

	// In: body
	Payload *genmodel.DriverEndpoint `json:"body,omitempty"`
}

// NewGetDriverEndpointOK creates GetDriverEndpointOK with default headers values
func NewGetDriverEndpointOK() *GetDriverEndpointOK {
	return &GetDriverEndpointOK{}
}

// WithPayload adds the payload to the get driver endpoint o k response
func (o *GetDriverEndpointOK) WithPayload(payload *genmodel.DriverEndpoint) *GetDriverEndpointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get driver endpoint o k response
func (o *GetDriverEndpointOK) SetPayload(payload *genmodel.DriverEndpoint) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDriverEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetDriverEndpointNotFound Not Found

swagger:response getDriverEndpointNotFound
*/
type GetDriverEndpointNotFound struct {
}

// NewGetDriverEndpointNotFound creates GetDriverEndpointNotFound with default headers values
func NewGetDriverEndpointNotFound() *GetDriverEndpointNotFound {
	return &GetDriverEndpointNotFound{}
}

// WriteResponse to the client
func (o *GetDriverEndpointNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetDriverEndpointInternalServerError Unexpected error

swagger:response getDriverEndpointInternalServerError
*/
type GetDriverEndpointInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewGetDriverEndpointInternalServerError creates GetDriverEndpointInternalServerError with default headers values
func NewGetDriverEndpointInternalServerError() *GetDriverEndpointInternalServerError {
	return &GetDriverEndpointInternalServerError{}
}

// WithPayload adds the payload to the get driver endpoint internal server error response
func (o *GetDriverEndpointInternalServerError) WithPayload(payload string) *GetDriverEndpointInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get driver endpoint internal server error response
func (o *GetDriverEndpointInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDriverEndpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
