package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PingDriverEndpointOK OK

swagger:response pingDriverEndpointOK
*/
type PingDriverEndpointOK struct {
}

// NewPingDriverEndpointOK creates PingDriverEndpointOK with default headers values
func NewPingDriverEndpointOK() *PingDriverEndpointOK {
	return &PingDriverEndpointOK{}
}

// WriteResponse to the client
func (o *PingDriverEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*PingDriverEndpointNotFound Not Found

swagger:response pingDriverEndpointNotFound
*/
type PingDriverEndpointNotFound struct {
}

// NewPingDriverEndpointNotFound creates PingDriverEndpointNotFound with default headers values
func NewPingDriverEndpointNotFound() *PingDriverEndpointNotFound {
	return &PingDriverEndpointNotFound{}
}

// WriteResponse to the client
func (o *PingDriverEndpointNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*PingDriverEndpointInternalServerError Unexpected error

swagger:response pingDriverEndpointInternalServerError
*/
type PingDriverEndpointInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewPingDriverEndpointInternalServerError creates PingDriverEndpointInternalServerError with default headers values
func NewPingDriverEndpointInternalServerError() *PingDriverEndpointInternalServerError {
	return &PingDriverEndpointInternalServerError{}
}

// WithPayload adds the payload to the ping driver endpoint internal server error response
func (o *PingDriverEndpointInternalServerError) WithPayload(payload string) *PingDriverEndpointInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ping driver endpoint internal server error response
func (o *PingDriverEndpointInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PingDriverEndpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
