package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*UpdateDriverEndpointOK Sucessful response

swagger:response updateDriverEndpointOK
*/
type UpdateDriverEndpointOK struct {

	// In: body
	Payload *genmodel.DriverEndpoint `json:"body,omitempty"`
}

// NewUpdateDriverEndpointOK creates UpdateDriverEndpointOK with default headers values
func NewUpdateDriverEndpointOK() *UpdateDriverEndpointOK {
	return &UpdateDriverEndpointOK{}
}

// WithPayload adds the payload to the update driver endpoint o k response
func (o *UpdateDriverEndpointOK) WithPayload(payload *genmodel.DriverEndpoint) *UpdateDriverEndpointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update driver endpoint o k response
func (o *UpdateDriverEndpointOK) SetPayload(payload *genmodel.DriverEndpoint) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDriverEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateDriverEndpointNotFound Not Found

swagger:response updateDriverEndpointNotFound
*/
type UpdateDriverEndpointNotFound struct {
}

// NewUpdateDriverEndpointNotFound creates UpdateDriverEndpointNotFound with default headers values
func NewUpdateDriverEndpointNotFound() *UpdateDriverEndpointNotFound {
	return &UpdateDriverEndpointNotFound{}
}

// WriteResponse to the client
func (o *UpdateDriverEndpointNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*UpdateDriverEndpointConflict Conflict

swagger:response updateDriverEndpointConflict
*/
type UpdateDriverEndpointConflict struct {
}

// NewUpdateDriverEndpointConflict creates UpdateDriverEndpointConflict with default headers values
func NewUpdateDriverEndpointConflict() *UpdateDriverEndpointConflict {
	return &UpdateDriverEndpointConflict{}
}

// WriteResponse to the client
func (o *UpdateDriverEndpointConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}

/*UpdateDriverEndpointInternalServerError Unexpected error

swagger:response updateDriverEndpointInternalServerError
*/
type UpdateDriverEndpointInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewUpdateDriverEndpointInternalServerError creates UpdateDriverEndpointInternalServerError with default headers values
func NewUpdateDriverEndpointInternalServerError() *UpdateDriverEndpointInternalServerError {
	return &UpdateDriverEndpointInternalServerError{}
}

// WithPayload adds the payload to the update driver endpoint internal server error response
func (o *UpdateDriverEndpointInternalServerError) WithPayload(payload string) *UpdateDriverEndpointInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update driver endpoint internal server error response
func (o *UpdateDriverEndpointInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDriverEndpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
