package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateDriverEndpointHandlerFunc turns a function with the right signature into a update driver endpoint handler
type UpdateDriverEndpointHandlerFunc func(UpdateDriverEndpointParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDriverEndpointHandlerFunc) Handle(params UpdateDriverEndpointParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateDriverEndpointHandler interface for that can handle valid update driver endpoint params
type UpdateDriverEndpointHandler interface {
	Handle(UpdateDriverEndpointParams, interface{}) middleware.Responder
}

// NewUpdateDriverEndpoint creates a new http.Handler for the update driver endpoint operation
func NewUpdateDriverEndpoint(ctx *middleware.Context, handler UpdateDriverEndpointHandler) *UpdateDriverEndpoint {
	return &UpdateDriverEndpoint{Context: ctx, Handler: handler}
}

/*UpdateDriverEndpoint swagger:route PUT /driver_endpoints/{driver_endpoint_id} updateDriverEndpoint

Update a driver endpoint


*/
type UpdateDriverEndpoint struct {
	Context *middleware.Context
	Handler UpdateDriverEndpointHandler
}

func (o *UpdateDriverEndpoint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateDriverEndpointParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
