package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	"mysql-driver/models"
)

// NewCreateWorkspaceParams creates a new CreateWorkspaceParams object
// with the default values initialized.
func NewCreateWorkspaceParams() CreateWorkspaceParams {
	var ()
	return CreateWorkspaceParams{}
}

// CreateWorkspaceParams contains all the bound params for the create workspace operation
// typically these are obtained from a http.Request
//
// swagger:parameters createWorkspace
type CreateWorkspaceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The service JSON you want to post
	  Required: true
	  In: body
	*/
	CreateWorkspaceRequest *models.ServiceManagerWorkspaceCreateRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateWorkspaceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if httpkit.HasBody(r) {
		defer r.Body.Close()
		var body models.ServiceManagerWorkspaceCreateRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("createWorkspaceRequest", "body"))
			} else {
				res = append(res, errors.NewParseError("createWorkspaceRequest", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CreateWorkspaceRequest = &body
			}
		}

	} else {
		res = append(res, errors.Required("createWorkspaceRequest", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
