package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"mysql-driver/models"
)

/*DeleteWorkspaceOK delete workspace

swagger:response deleteWorkspaceOK
*/
type DeleteWorkspaceOK struct {
}

// NewDeleteWorkspaceOK creates DeleteWorkspaceOK with default headers values
func NewDeleteWorkspaceOK() *DeleteWorkspaceOK {
	return &DeleteWorkspaceOK{}
}

// WriteResponse to the client
func (o *DeleteWorkspaceOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*DeleteWorkspaceDefault generic error response

swagger:response deleteWorkspaceDefault
*/
type DeleteWorkspaceDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWorkspaceDefault creates DeleteWorkspaceDefault with default headers values
func NewDeleteWorkspaceDefault(code int) *DeleteWorkspaceDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteWorkspaceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete workspace default response
func (o *DeleteWorkspaceDefault) WithStatusCode(code int) *DeleteWorkspaceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete workspace default response
func (o *DeleteWorkspaceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete workspace default response
func (o *DeleteWorkspaceDefault) WithPayload(payload *models.Error) *DeleteWorkspaceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workspace default response
func (o *DeleteWorkspaceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkspaceDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
