package connection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new connection API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for connection API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*
CreateConnection Create new connection
*/
func (a *Client) CreateConnection(params *CreateConnectionParams) (*CreateConnectionCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateConnectionParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "createConnection",
		Method:             "POST",
		PathPattern:        "/workspaces/{workspace_id}/connections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateConnectionReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateConnectionCreated), nil
}

/*
DeleteConnection Delete specified connection
*/
func (a *Client) DeleteConnection(params *DeleteConnectionParams) (*DeleteConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteConnectionParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "deleteConnection",
		Method:             "DELETE",
		PathPattern:        "/workspaces/{workspace_id}/connections/{connection_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteConnectionReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteConnectionOK), nil
}

/*
GetConnection Get the details for the specified
*/
func (a *Client) GetConnection(params *GetConnectionParams) (*GetConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConnectionParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getConnection",
		Method:             "GET",
		PathPattern:        "/workspaces/{workspace_id}/connections/{connection_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetConnectionReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetConnectionOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}
