package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*ServiceManagerWorkspaceCreateRequest service manager workspace create request

swagger:model ServiceManagerWorkspaceCreateRequest
*/
type ServiceManagerWorkspaceCreateRequest struct {

	/* key value map with connection details (Service manager won't interpret the details of the map it will send this back to the requester as is)
	 */
	Details map[string]interface{} `json:"details,omitempty"`

	/* Workspace id

	Required: true
	*/
	WorkspaceID string `json:"workspace_id"`
}

// Validate validates this service manager workspace create request
func (m *ServiceManagerWorkspaceCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetails(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateWorkspaceID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceManagerWorkspaceCreateRequest) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.Details) { // not required
		return nil
	}

	if swag.IsZero(m.Details) { // not required
		return nil
	}

	return nil
}

func (m *ServiceManagerWorkspaceCreateRequest) validateWorkspaceID(formats strfmt.Registry) error {

	if err := validate.RequiredString("workspace_id", "body", string(m.WorkspaceID)); err != nil {
		return err
	}

	return nil
}
