package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*CreateInstanceCreated Instance created

swagger:response createInstanceCreated
*/
type CreateInstanceCreated struct {

	// In: body
	Payload *genmodel.Instance `json:"body,omitempty"`
}

// NewCreateInstanceCreated creates CreateInstanceCreated with default headers values
func NewCreateInstanceCreated() *CreateInstanceCreated {
	return &CreateInstanceCreated{}
}

// WithPayload adds the payload to the create instance created response
func (o *CreateInstanceCreated) WithPayload(payload *genmodel.Instance) *CreateInstanceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create instance created response
func (o *CreateInstanceCreated) SetPayload(payload *genmodel.Instance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateInstanceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateInstanceConflict Conflict

swagger:response createInstanceConflict
*/
type CreateInstanceConflict struct {
}

// NewCreateInstanceConflict creates CreateInstanceConflict with default headers values
func NewCreateInstanceConflict() *CreateInstanceConflict {
	return &CreateInstanceConflict{}
}

// WriteResponse to the client
func (o *CreateInstanceConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}

/*CreateInstanceInternalServerError Unexpected error

swagger:response createInstanceInternalServerError
*/
type CreateInstanceInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewCreateInstanceInternalServerError creates CreateInstanceInternalServerError with default headers values
func NewCreateInstanceInternalServerError() *CreateInstanceInternalServerError {
	return &CreateInstanceInternalServerError{}
}

// WithPayload adds the payload to the create instance internal server error response
func (o *CreateInstanceInternalServerError) WithPayload(payload string) *CreateInstanceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create instance internal server error response
func (o *CreateInstanceInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateInstanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
