package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// NewCreateInstanceParams creates a new CreateInstanceParams object
// with the default values initialized.
func NewCreateInstanceParams() CreateInstanceParams {
	var ()
	return CreateInstanceParams{}
}

// CreateInstanceParams contains all the bound params for the create instance operation
// typically these are obtained from a http.Request
//
// swagger:parameters createInstance
type CreateInstanceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Instance to be created
	  Required: true
	  In: body
	*/
	Instance *genmodel.Instance
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateInstanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body genmodel.Instance
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("instance", "body"))
			} else {
				res = append(res, errors.NewParseError("instance", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Instance = &body
			}
		}

	} else {
		res = append(res, errors.Required("instance", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
