package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*CreateDialCreated Sucessfull response

swagger:response createDialCreated
*/
type CreateDialCreated struct {

	// In: body
	Payload *genmodel.Dial `json:"body,omitempty"`
}

// NewCreateDialCreated creates CreateDialCreated with default headers values
func NewCreateDialCreated() *CreateDialCreated {
	return &CreateDialCreated{}
}

// WithPayload adds the payload to the create dial created response
func (o *CreateDialCreated) WithPayload(payload *genmodel.Dial) *CreateDialCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create dial created response
func (o *CreateDialCreated) SetPayload(payload *genmodel.Dial) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDialCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateDialInternalServerError Unexpected error

swagger:response createDialInternalServerError
*/
type CreateDialInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewCreateDialInternalServerError creates CreateDialInternalServerError with default headers values
func NewCreateDialInternalServerError() *CreateDialInternalServerError {
	return &CreateDialInternalServerError{}
}

// WithPayload adds the payload to the create dial internal server error response
func (o *CreateDialInternalServerError) WithPayload(payload string) *CreateDialInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create dial internal server error response
func (o *CreateDialInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDialInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
