package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// DeleteDriverHandlerFunc turns a function with the right signature into a delete driver handler
type DeleteDriverHandlerFunc func(DeleteDriverParams) error

func (fn DeleteDriverHandlerFunc) Handle(params DeleteDriverParams) error {
	return fn(params)
}

// DeleteDriverHandler interface for that can handle valid delete driver params
type DeleteDriverHandler interface {
	Handle(DeleteDriverParams) error
}

// NewDeleteDriver creates a new http.Handler for the delete driver operation
func NewDeleteDriver(ctx *middleware.Context, handler DeleteDriverHandler) *DeleteDriver {
	return &DeleteDriver{Context: ctx, Handler: handler}
}

/*
Update driver
*/
type DeleteDriver struct {
	Context *middleware.Context
	Params  DeleteDriverParams
	Handler DeleteDriverHandler
}

func (o *DeleteDriver) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, nil)

}
