package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteInstanceNoContent Instance deleted

swagger:response deleteInstanceNoContent
*/
type DeleteInstanceNoContent struct {
}

// NewDeleteInstanceNoContent creates DeleteInstanceNoContent with default headers values
func NewDeleteInstanceNoContent() *DeleteInstanceNoContent {
	return &DeleteInstanceNoContent{}
}

// WriteResponse to the client
func (o *DeleteInstanceNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*DeleteInstanceNotFound Not Found

swagger:response deleteInstanceNotFound
*/
type DeleteInstanceNotFound struct {
}

// NewDeleteInstanceNotFound creates DeleteInstanceNotFound with default headers values
func NewDeleteInstanceNotFound() *DeleteInstanceNotFound {
	return &DeleteInstanceNotFound{}
}

// WriteResponse to the client
func (o *DeleteInstanceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*DeleteInstanceInternalServerError Unexpected error

swagger:response deleteInstanceInternalServerError
*/
type DeleteInstanceInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewDeleteInstanceInternalServerError creates DeleteInstanceInternalServerError with default headers values
func NewDeleteInstanceInternalServerError() *DeleteInstanceInternalServerError {
	return &DeleteInstanceInternalServerError{}
}

// WithPayload adds the payload to the delete instance internal server error response
func (o *DeleteInstanceInternalServerError) WithPayload(payload string) *DeleteInstanceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete instance internal server error response
func (o *DeleteInstanceInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteInstanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
