package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*DeleteDriverInstanceNoContent Driver deleted

swagger:response deleteDriverInstanceNoContent
*/
type DeleteDriverInstanceNoContent struct {
}

// WriteResponse to the client
func (o *DeleteDriverInstanceNoContent) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(204)
}

/*DeleteDriverInstanceNotFound Not Found

swagger:response deleteDriverInstanceNotFound
*/
type DeleteDriverInstanceNotFound struct {
}

// WriteResponse to the client
func (o *DeleteDriverInstanceNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
}

/*DeleteDriverInstanceInternalServerError Unexpected error

swagger:response deleteDriverInstanceInternalServerError
*/
type DeleteDriverInstanceInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *DeleteDriverInstanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
