package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// DeleteDriverInstanceHandlerFunc turns a function with the right signature into a delete driver instance handler
type DeleteDriverInstanceHandlerFunc func(DeleteDriverInstanceParams) error

func (fn DeleteDriverInstanceHandlerFunc) Handle(params DeleteDriverInstanceParams) error {
	return fn(params)
}

// DeleteDriverInstanceHandler interface for that can handle valid delete driver instance params
type DeleteDriverInstanceHandler interface {
	Handle(DeleteDriverInstanceParams) error
}

// NewDeleteDriverInstance creates a new http.Handler for the delete driver instance operation
func NewDeleteDriverInstance(ctx *middleware.Context, handler DeleteDriverInstanceHandler) DeleteDriverInstance {
	return DeleteDriverInstance{Context: ctx, Handler: handler}
}

/*
Delete a driver instance
*/
type DeleteDriverInstance struct {
	Context *middleware.Context
	Params  DeleteDriverInstanceParams
	Handler DeleteDriverInstanceHandler
}

func (o DeleteDriverInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, nil)

}
