package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteServicePlanParams creates a new DeleteServicePlanParams object
// with the default values initialized.
func NewDeleteServicePlanParams() DeleteServicePlanParams {
	var ()
	return DeleteServicePlanParams{}
}

// DeleteServicePlanParams contains all the bound params for the delete service plan operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteServicePlan
type DeleteServicePlanParams struct {
	/*ID of the plan
	  Required: true
	  In: path
	*/
	PlanID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteServicePlanParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	rPlanID, rhkPlanID, _ := route.Params.GetOK("plan_id")
	if err := o.bindPlanID(rPlanID, rhkPlanID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteServicePlanParams) bindPlanID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.PlanID = raw

	return nil
}
