package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*DeleteDialNoContent Sucessfull response

swagger:response deleteDialNoContent
*/
type DeleteDialNoContent struct {
}

// WriteResponse to the client
func (o *DeleteDialNoContent) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(204)
}

/*DeleteDialNotFound Not Found

swagger:response deleteDialNotFound
*/
type DeleteDialNotFound struct {
}

// WriteResponse to the client
func (o *DeleteDialNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
}

/*DeleteDialInternalServerError Unexpected error

swagger:response deleteDialInternalServerError
*/
type DeleteDialInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *DeleteDialInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
