package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// GetServiceByIDHandlerFunc turns a function with the right signature into a get service by ID handler
type GetServiceByIDHandlerFunc func() (*genmodel.Service, error)

func (fn GetServiceByIDHandlerFunc) Handle() (*genmodel.Service, error) {
	return fn()
}

// GetServiceByIDHandler interface for that can handle valid get service by ID params
type GetServiceByIDHandler interface {
	Handle() (*genmodel.Service, error)
}

// NewGetServiceByID creates a new http.Handler for the get service by ID operation
func NewGetServiceByID(ctx *middleware.Context, handler GetServiceByIDHandler) *GetServiceByID {
	return &GetServiceByID{Context: ctx, Handler: handler}
}

/*
Gets the `service` with the id **serviceID**
*/
type GetServiceByID struct {
	Context *middleware.Context
	Handler GetServiceByIDHandler
}

func (o *GetServiceByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res, err := o.Handler.Handle() // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, res)

}
