package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetServiceHandlerFunc turns a function with the right signature into a get service handler
type GetServiceHandlerFunc func(GetServiceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetServiceHandlerFunc) Handle(params GetServiceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetServiceHandler interface for that can handle valid get service params
type GetServiceHandler interface {
	Handle(GetServiceParams, interface{}) middleware.Responder
}

// NewGetService creates a new http.Handler for the get service operation
func NewGetService(ctx *middleware.Context, handler GetServiceHandler) *GetService {
	return &GetService{Context: ctx, Handler: handler}
}

/*GetService swagger:route GET /services/{service_id} getService

Gets the `service` with the id **serviceID**

*/
type GetService struct {
	Context *middleware.Context
	Handler GetServiceHandler
}

func (o *GetService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetServiceParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
