package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*GetDriverOK OK

swagger:response getDriverOK
*/
type GetDriverOK struct {

	// In: body
	Payload *genmodel.Driver `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *GetDriverOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetDriverNotFound Not Found

swagger:response getDriverNotFound
*/
type GetDriverNotFound struct {
}

// WriteResponse to the client
func (o *GetDriverNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
}

/*GetDriverInternalServerError Unexpected error

swagger:response getDriverInternalServerError
*/
type GetDriverInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *GetDriverInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
