package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// GetDriverConfigsHandlerFunc turns a function with the right signature into a get driver configs handler
type GetDriverConfigsHandlerFunc func() (*[]genmodel.DriverConfig, error)

func (fn GetDriverConfigsHandlerFunc) Handle() (*[]genmodel.DriverConfig, error) {
	return fn()
}

// GetDriverConfigsHandler interface for that can handle valid get driver configs params
type GetDriverConfigsHandler interface {
	Handle() (*[]genmodel.DriverConfig, error)
}

// NewGetDriverConfigs creates a new http.Handler for the get driver configs operation
func NewGetDriverConfigs(ctx *middleware.Context, handler GetDriverConfigsHandler) *GetDriverConfigs {
	return &GetDriverConfigs{Context: ctx, Handler: handler}
}

/*
Gets all driver configurations

*/
type GetDriverConfigs struct {
	Context *middleware.Context
	Handler GetDriverConfigsHandler
}

func (o *GetDriverConfigs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res, err := o.Handler.Handle() // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, res)

}
