package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*GetDriverInstanceOK OK

swagger:response getDriverInstanceOK
*/
type GetDriverInstanceOK struct {

	// In: body
	Payload *genmodel.DriverInstance `json:"body,omitempty"`
}

// NewGetDriverInstanceOK creates GetDriverInstanceOK with default headers values
func NewGetDriverInstanceOK() *GetDriverInstanceOK {
	return &GetDriverInstanceOK{}
}

// WithPayload adds the payload to the get driver instance o k response
func (o *GetDriverInstanceOK) WithPayload(payload *genmodel.DriverInstance) *GetDriverInstanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get driver instance o k response
func (o *GetDriverInstanceOK) SetPayload(payload *genmodel.DriverInstance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDriverInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetDriverInstanceNotFound Not Found

swagger:response getDriverInstanceNotFound
*/
type GetDriverInstanceNotFound struct {
}

// NewGetDriverInstanceNotFound creates GetDriverInstanceNotFound with default headers values
func NewGetDriverInstanceNotFound() *GetDriverInstanceNotFound {
	return &GetDriverInstanceNotFound{}
}

// WriteResponse to the client
func (o *GetDriverInstanceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetDriverInstanceInternalServerError Unexpected error

swagger:response getDriverInstanceInternalServerError
*/
type GetDriverInstanceInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewGetDriverInstanceInternalServerError creates GetDriverInstanceInternalServerError with default headers values
func NewGetDriverInstanceInternalServerError() *GetDriverInstanceInternalServerError {
	return &GetDriverInstanceInternalServerError{}
}

// WithPayload adds the payload to the get driver instance internal server error response
func (o *GetDriverInstanceInternalServerError) WithPayload(payload string) *GetDriverInstanceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get driver instance internal server error response
func (o *GetDriverInstanceInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDriverInstanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
