package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// GetServicePlansHandlerFunc turns a function with the right signature into a get service plans handler
type GetServicePlansHandlerFunc func() (*[]genmodel.Plan, error)

func (fn GetServicePlansHandlerFunc) Handle() (*[]genmodel.Plan, error) {
	return fn()
}

// GetServicePlansHandler interface for that can handle valid get service plans params
type GetServicePlansHandler interface {
	Handle() (*[]genmodel.Plan, error)
}

// NewGetServicePlans creates a new http.Handler for the get service plans operation
func NewGetServicePlans(ctx *middleware.Context, handler GetServicePlansHandler) *GetServicePlans {
	return &GetServicePlans{Context: ctx, Handler: handler}
}

/*
Gets the `plans` for the **serviceID**
*/
type GetServicePlans struct {
	Context *middleware.Context
	Handler GetServicePlansHandler
}

func (o *GetServicePlans) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res, err := o.Handler.Handle() // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, res)

}
