package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*GetDriverOK OK

swagger:response getDriverOK
*/
type GetDriverOK struct {

	// In: body
	Payload *genmodel.Driver `json:"body,omitempty"`
}

// NewGetDriverOK creates GetDriverOK with default headers values
func NewGetDriverOK() *GetDriverOK {
	return &GetDriverOK{}
}

// WithPayload adds the payload to the get driver o k response
func (o *GetDriverOK) WithPayload(payload *genmodel.Driver) *GetDriverOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get driver o k response
func (o *GetDriverOK) SetPayload(payload *genmodel.Driver) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDriverOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetDriverNotFound Not Found

swagger:response getDriverNotFound
*/
type GetDriverNotFound struct {
}

// NewGetDriverNotFound creates GetDriverNotFound with default headers values
func NewGetDriverNotFound() *GetDriverNotFound {
	return &GetDriverNotFound{}
}

// WriteResponse to the client
func (o *GetDriverNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetDriverInternalServerError Unexpected error

swagger:response getDriverInternalServerError
*/
type GetDriverInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewGetDriverInternalServerError creates GetDriverInternalServerError with default headers values
func NewGetDriverInternalServerError() *GetDriverInternalServerError {
	return &GetDriverInternalServerError{}
}

// WithPayload adds the payload to the get driver internal server error response
func (o *GetDriverInternalServerError) WithPayload(payload string) *GetDriverInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get driver internal server error response
func (o *GetDriverInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDriverInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
