package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*GetServiceOK Sucessfull response

swagger:response getServiceOK
*/
type GetServiceOK struct {

	// In: body
	Payload *genmodel.Service `json:"body,omitempty"`
}

// NewGetServiceOK creates GetServiceOK with default headers values
func NewGetServiceOK() *GetServiceOK {
	return &GetServiceOK{}
}

// WithPayload adds the payload to the get service o k response
func (o *GetServiceOK) WithPayload(payload *genmodel.Service) *GetServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service o k response
func (o *GetServiceOK) SetPayload(payload *genmodel.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetServiceNotFound Not Found

swagger:response getServiceNotFound
*/
type GetServiceNotFound struct {
}

// NewGetServiceNotFound creates GetServiceNotFound with default headers values
func NewGetServiceNotFound() *GetServiceNotFound {
	return &GetServiceNotFound{}
}

// WriteResponse to the client
func (o *GetServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetServiceInternalServerError Unexpected error

swagger:response getServiceInternalServerError
*/
type GetServiceInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewGetServiceInternalServerError creates GetServiceInternalServerError with default headers values
func NewGetServiceInternalServerError() *GetServiceInternalServerError {
	return &GetServiceInternalServerError{}
}

// WithPayload adds the payload to the get service internal server error response
func (o *GetServiceInternalServerError) WithPayload(payload string) *GetServiceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get service internal server error response
func (o *GetServiceInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServiceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
