package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// GetServiceHandlerFunc turns a function with the right signature into a get service handler
type GetServiceHandlerFunc func(GetServiceParams) (*genmodel.Service, error)

func (fn GetServiceHandlerFunc) Handle(params GetServiceParams) (*genmodel.Service, error) {
	return fn(params)
}

// GetServiceHandler interface for that can handle valid get service params
type GetServiceHandler interface {
	Handle(GetServiceParams) (*genmodel.Service, error)
}

// NewGetService creates a new http.Handler for the get service operation
func NewGetService(ctx *middleware.Context, handler GetServiceHandler) *GetService {
	return &GetService{Context: ctx, Handler: handler}
}

/*
Gets the `service` with the id **serviceID**
*/
type GetService struct {
	Context *middleware.Context
	Params  GetServiceParams
	Handler GetServiceHandler
}

func (o *GetService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res, err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, res)

}
