package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// GetDriverInstancesHandlerFunc turns a function with the right signature into a get driver instances handler
type GetDriverInstancesHandlerFunc func(GetDriverInstancesParams) (*[]genmodel.DriverInstance, error)

func (fn GetDriverInstancesHandlerFunc) Handle(params GetDriverInstancesParams) (*[]genmodel.DriverInstance, error) {
	return fn(params)
}

// GetDriverInstancesHandler interface for that can handle valid get driver instances params
type GetDriverInstancesHandler interface {
	Handle(GetDriverInstancesParams) (*[]genmodel.DriverInstance, error)
}

// NewGetDriverInstances creates a new http.Handler for the get driver instances operation
func NewGetDriverInstances(ctx *middleware.Context, handler GetDriverInstancesHandler) *GetDriverInstances {
	return &GetDriverInstances{Context: ctx, Handler: handler}
}

/*
Gets all driver configurations

*/
type GetDriverInstances struct {
	Context *middleware.Context
	Params  GetDriverInstancesParams
	Handler GetDriverInstancesHandler
}

func (o *GetDriverInstances) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res, err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, res)

}
