package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// PingDriverInstanceHandlerFunc turns a function with the right signature into a ping driver instance handler
type PingDriverInstanceHandlerFunc func(PingDriverInstanceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PingDriverInstanceHandlerFunc) Handle(params PingDriverInstanceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PingDriverInstanceHandler interface for that can handle valid ping driver instance params
type PingDriverInstanceHandler interface {
	Handle(PingDriverInstanceParams, interface{}) middleware.Responder
}

// NewPingDriverInstance creates a new http.Handler for the ping driver instance operation
func NewPingDriverInstance(ctx *middleware.Context, handler PingDriverInstanceHandler) *PingDriverInstance {
	return &PingDriverInstance{Context: ctx, Handler: handler}
}

/*PingDriverInstance swagger:route GET /driver_instances/{driver_instance_id}/ping pingDriverInstance

Pings the driver


*/
type PingDriverInstance struct {
	Context *middleware.Context
	Handler PingDriverInstanceHandler
}

func (o *PingDriverInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPingDriverInstanceParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
