package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*UpdateDialOK Sucessfull response

swagger:response updateDialOK
*/
type UpdateDialOK struct {

	// In: body
	Payload *genmodel.Dial `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *UpdateDialOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateDialNotFound Not Found

swagger:response updateDialNotFound
*/
type UpdateDialNotFound struct {
}

// WriteResponse to the client
func (o *UpdateDialNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
}

/*UpdateDialInternalServerError Unexpected error

swagger:response updateDialInternalServerError
*/
type UpdateDialInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *UpdateDialInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
