package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// UpdateServiceHandlerFunc turns a function with the right signature into a update service handler
type UpdateServiceHandlerFunc func(UpdateServiceParams) error

func (fn UpdateServiceHandlerFunc) Handle(params UpdateServiceParams) error {
	return fn(params)
}

// UpdateServiceHandler interface for that can handle valid update service params
type UpdateServiceHandler interface {
	Handle(UpdateServiceParams) error
}

// NewUpdateService creates a new http.Handler for the update service operation
func NewUpdateService(ctx *middleware.Context, handler UpdateServiceHandler) *UpdateService {
	return &UpdateService{Context: ctx, Handler: handler}
}

/*
Updates the `service` with the id **serviceID**
*/
type UpdateService struct {
	Context *middleware.Context
	Params  UpdateServiceParams
	Handler UpdateServiceHandler
}

func (o *UpdateService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, nil)

}
