package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*UpdateServiceOK Sucessfull response

swagger:response updateServiceOK
*/
type UpdateServiceOK struct {

	// In: body
	Payload *genmodel.Service `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *UpdateServiceOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateServiceNotFound Not Found

swagger:response updateServiceNotFound
*/
type UpdateServiceNotFound struct {
}

// WriteResponse to the client
func (o *UpdateServiceNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
}

/*UpdateServiceInternalServerError Unexpected error

swagger:response updateServiceInternalServerError
*/
type UpdateServiceInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *UpdateServiceInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
