package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*UpdateCatalogOK Successful response

swagger:response updateCatalogOK
*/
type UpdateCatalogOK struct {
}

// NewUpdateCatalogOK creates UpdateCatalogOK with default headers values
func NewUpdateCatalogOK() *UpdateCatalogOK {
	return &UpdateCatalogOK{}
}

// WriteResponse to the client
func (o *UpdateCatalogOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*UpdateCatalogInternalServerError Unexpected error

swagger:response updateCatalogInternalServerError
*/
type UpdateCatalogInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewUpdateCatalogInternalServerError creates UpdateCatalogInternalServerError with default headers values
func NewUpdateCatalogInternalServerError() *UpdateCatalogInternalServerError {
	return &UpdateCatalogInternalServerError{}
}

// WithPayload adds the payload to the update catalog internal server error response
func (o *UpdateCatalogInternalServerError) WithPayload(payload string) *UpdateCatalogInternalServerError {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *UpdateCatalogInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
