package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateDriverInstanceHandlerFunc turns a function with the right signature into a update driver instance handler
type UpdateDriverInstanceHandlerFunc func(UpdateDriverInstanceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDriverInstanceHandlerFunc) Handle(params UpdateDriverInstanceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateDriverInstanceHandler interface for that can handle valid update driver instance params
type UpdateDriverInstanceHandler interface {
	Handle(UpdateDriverInstanceParams, interface{}) middleware.Responder
}

// NewUpdateDriverInstance creates a new http.Handler for the update driver instance operation
func NewUpdateDriverInstance(ctx *middleware.Context, handler UpdateDriverInstanceHandler) *UpdateDriverInstance {
	return &UpdateDriverInstance{Context: ctx, Handler: handler}
}

/*UpdateDriverInstance swagger:route PUT /driver_instances/{driver_instance_id} updateDriverInstance

Update a driver instance


*/
type UpdateDriverInstance struct {
	Context *middleware.Context
	Handler UpdateDriverInstanceHandler
}

func (o *UpdateDriverInstance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUpdateDriverInstanceParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
