package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// UpdateBrokerInfoHandlerFunc turns a function with the right signature into a update broker info handler
type UpdateBrokerInfoHandlerFunc func(UpdateBrokerInfoParams) (*genmodel.Broker, error)

func (fn UpdateBrokerInfoHandlerFunc) Handle(params UpdateBrokerInfoParams) (*genmodel.Broker, error) {
	return fn(params)
}

// UpdateBrokerInfoHandler interface for that can handle valid update broker info params
type UpdateBrokerInfoHandler interface {
	Handle(UpdateBrokerInfoParams) (*genmodel.Broker, error)
}

// NewUpdateBrokerInfo creates a new http.Handler for the update broker info operation
func NewUpdateBrokerInfo(ctx *middleware.Context, handler UpdateBrokerInfoHandler) *UpdateBrokerInfo {
	return &UpdateBrokerInfo{Context: ctx, Handler: handler}
}

/*
Sets the broker api connection info

*/
type UpdateBrokerInfo struct {
	Context *middleware.Context
	Params  UpdateBrokerInfoParams
	Handler UpdateBrokerInfoHandler
}

func (o *UpdateBrokerInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res, err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, res)

}
