package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// NewUpdateDriverInstanceParams creates a new UpdateDriverInstanceParams object
// with the default values initialized.
func NewUpdateDriverInstanceParams() UpdateDriverInstanceParams {
	var ()
	return UpdateDriverInstanceParams{}
}

// UpdateDriverInstanceParams contains all the bound params for the update driver instance operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateDriverInstance
type UpdateDriverInstanceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Add driver_config
	  Required: true
	  In: body
	*/
	DriverConfig *genmodel.DriverInstance
	/*Driver Instance ID
	  Required: true
	  In: path
	*/
	DriverInstanceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateDriverInstanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body genmodel.DriverInstance
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("driverConfig", "body"))
			} else {
				res = append(res, errors.NewParseError("driverConfig", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.DriverConfig = &body
			}
		}

	} else {
		res = append(res, errors.Required("driverConfig", "body"))
	}

	rDriverInstanceID, rhkDriverInstanceID, _ := route.Params.GetOK("driver_instance_id")
	if err := o.bindDriverInstanceID(rDriverInstanceID, rhkDriverInstanceID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateDriverInstanceParams) bindDriverInstanceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DriverInstanceID = raw

	return nil
}
