package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// NewUpdateInstanceParams creates a new UpdateInstanceParams object
// with the default values initialized.
func NewUpdateInstanceParams() UpdateInstanceParams {
	var ()
	return UpdateInstanceParams{}
}

// UpdateInstanceParams contains all the bound params for the update instance operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateInstance
type UpdateInstanceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Add instance_config
	  Required: true
	  In: body
	*/
	InstanceConfig *genmodel.Instance
	/*Instance ID
	  Required: true
	  In: path
	*/
	InstanceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateInstanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body genmodel.Instance
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("instanceConfig", "body"))
			} else {
				res = append(res, errors.NewParseError("instanceConfig", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.InstanceConfig = &body
			}
		}

	} else {
		res = append(res, errors.Required("instanceConfig", "body"))
	}

	rInstanceID, rhkInstanceID, _ := route.Params.GetOK("instance_id")
	if err := o.bindInstanceID(rInstanceID, rhkInstanceID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateInstanceParams) bindInstanceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.InstanceID = raw

	return nil
}
