package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

/*UpdateInstanceOK Sucessfull response

swagger:response updateInstanceOK
*/
type UpdateInstanceOK struct {

	// In: body
	Payload *genmodel.Instance `json:"body,omitempty"`
}

// NewUpdateInstanceOK creates UpdateInstanceOK with default headers values
func NewUpdateInstanceOK() *UpdateInstanceOK {
	return &UpdateInstanceOK{}
}

// WithPayload adds the payload to the update instance o k response
func (o *UpdateInstanceOK) WithPayload(payload *genmodel.Instance) *UpdateInstanceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update instance o k response
func (o *UpdateInstanceOK) SetPayload(payload *genmodel.Instance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateInstanceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateInstanceNotFound Not Found

swagger:response updateInstanceNotFound
*/
type UpdateInstanceNotFound struct {
}

// NewUpdateInstanceNotFound creates UpdateInstanceNotFound with default headers values
func NewUpdateInstanceNotFound() *UpdateInstanceNotFound {
	return &UpdateInstanceNotFound{}
}

// WriteResponse to the client
func (o *UpdateInstanceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*UpdateInstanceConflict Conflict

swagger:response updateInstanceConflict
*/
type UpdateInstanceConflict struct {
}

// NewUpdateInstanceConflict creates UpdateInstanceConflict with default headers values
func NewUpdateInstanceConflict() *UpdateInstanceConflict {
	return &UpdateInstanceConflict{}
}

// WriteResponse to the client
func (o *UpdateInstanceConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}

/*UpdateInstanceInternalServerError Unexpected error

swagger:response updateInstanceInternalServerError
*/
type UpdateInstanceInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// NewUpdateInstanceInternalServerError creates UpdateInstanceInternalServerError with default headers values
func NewUpdateInstanceInternalServerError() *UpdateInstanceInternalServerError {
	return &UpdateInstanceInternalServerError{}
}

// WithPayload adds the payload to the update instance internal server error response
func (o *UpdateInstanceInternalServerError) WithPayload(payload string) *UpdateInstanceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update instance internal server error response
func (o *UpdateInstanceInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateInstanceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
