package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// UpdateDriverHandlerFunc turns a function with the right signature into a update driver handler
type UpdateDriverHandlerFunc func(UpdateDriverParams) error

func (fn UpdateDriverHandlerFunc) Handle(params UpdateDriverParams) error {
	return fn(params)
}

// UpdateDriverHandler interface for that can handle valid update driver params
type UpdateDriverHandler interface {
	Handle(UpdateDriverParams) error
}

// NewUpdateDriver creates a new http.Handler for the update driver operation
func NewUpdateDriver(ctx *middleware.Context, handler UpdateDriverHandler) *UpdateDriver {
	return &UpdateDriver{Context: ctx, Handler: handler}
}

/*
Update driver
*/
type UpdateDriver struct {
	Context *middleware.Context
	Params  UpdateDriverParams
	Handler UpdateDriverHandler
}

func (o *UpdateDriver) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, nil)

}
