package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hpcloud/cf-usb/lib/genmodel"
)

// NewUpdateServicePlanParams creates a new UpdateServicePlanParams object
// with the default values initialized.
func NewUpdateServicePlanParams() UpdateServicePlanParams {
	var ()
	return UpdateServicePlanParams{}
}

// UpdateServicePlanParams contains all the bound params for the update service plan operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateServicePlan
type UpdateServicePlanParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Update plan
	  Required: true
	  In: body
	*/
	Plan *genmodel.Plan
	/*ID of the plan
	  Required: true
	  In: path
	*/
	PlanID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateServicePlanParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body genmodel.Plan
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("plan", "body"))
			} else {
				res = append(res, errors.NewParseError("plan", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Plan = &body
			}
		}

	} else {
		res = append(res, errors.Required("plan", "body"))
	}

	rPlanID, rhkPlanID, _ := route.Params.GetOK("plan_id")
	if err := o.bindPlanID(rPlanID, rhkPlanID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateServicePlanParams) bindPlanID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.PlanID = raw

	return nil
}
