package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UploadDriverHandlerFunc turns a function with the right signature into a upload driver handler
type UploadDriverHandlerFunc func(UploadDriverParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadDriverHandlerFunc) Handle(params UploadDriverParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UploadDriverHandler interface for that can handle valid upload driver params
type UploadDriverHandler interface {
	Handle(UploadDriverParams, interface{}) middleware.Responder
}

// NewUploadDriver creates a new http.Handler for the upload driver operation
func NewUploadDriver(ctx *middleware.Context, handler UploadDriverHandler) *UploadDriver {
	return &UploadDriver{Context: ctx, Handler: handler}
}

/*UploadDriver swagger:route PUT /drivers/{driver_id}/bits uploadDriver

Upload driver bits

*/
type UploadDriver struct {
	Context *middleware.Context
	Handler UploadDriverHandler
}

func (o *UploadDriver) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewUploadDriverParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
