package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// UploadDriverHandlerFunc turns a function with the right signature into a upload driver handler
type UploadDriverHandlerFunc func(UploadDriverParams) error

func (fn UploadDriverHandlerFunc) Handle(params UploadDriverParams) error {
	return fn(params)
}

// UploadDriverHandler interface for that can handle valid upload driver params
type UploadDriverHandler interface {
	Handle(UploadDriverParams) error
}

// NewUploadDriver creates a new http.Handler for the upload driver operation
func NewUploadDriver(ctx *middleware.Context, handler UploadDriverHandler) UploadDriver {
	return UploadDriver{Context: ctx, Handler: handler}
}

/*
Upload driver bits
*/
type UploadDriver struct {
	Context *middleware.Context
	Params  UploadDriverParams
	Handler UploadDriverHandler
}

func (o UploadDriver) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, &o.Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	err := o.Handler.Handle(o.Params) // actually handle the request
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	o.Context.Respond(rw, r, route.Produces, route, nil)

}
