package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"
)

/*UploadDriverOK Driver uploaded

swagger:response uploadDriverOK
*/
type UploadDriverOK struct {
}

// WriteResponse to the client
func (o *UploadDriverOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*UploadDriverNotFound Not Found

swagger:response uploadDriverNotFound
*/
type UploadDriverNotFound struct {
}

// WriteResponse to the client
func (o *UploadDriverNotFound) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(404)
}

/*UploadDriverInternalServerError Unexpected error

swagger:response uploadDriverInternalServerError
*/
type UploadDriverInternalServerError struct {

	// In: body
	Payload string `json:"body,omitempty"`
}

// WriteResponse to the client
func (o *UploadDriverInternalServerError) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
