package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUsbMgmtAPI creates a new UsbMgmt instance
func NewUsbMgmtAPI(spec *loads.Document) *UsbMgmtAPI {
	o := &UsbMgmtAPI{
		spec:            spec,
		handlers:        make(map[string]map[string]http.Handler),
		formats:         strfmt.Default,
		defaultConsumes: "application/json",
		defaultProduces: "application/json",
		ServerShutdown:  func() {},
	}

	return o
}

/*UsbMgmtAPI Universal service broker management API */
type UsbMgmtAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// AuthorizationAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	AuthorizationAuth func(string) (interface{}, error)

	// CreateDialHandler sets the operation handler for the create dial operation
	CreateDialHandler CreateDialHandler
	// CreateInstanceHandler sets the operation handler for the create instance operation
	CreateInstanceHandler CreateInstanceHandler
	// DeleteDialHandler sets the operation handler for the delete dial operation
	DeleteDialHandler DeleteDialHandler
	// DeleteInstanceHandler sets the operation handler for the delete instance operation
	DeleteInstanceHandler DeleteInstanceHandler
	// GetAllDialsHandler sets the operation handler for the get all dials operation
	GetAllDialsHandler GetAllDialsHandler
	// GetDialHandler sets the operation handler for the get dial operation
	GetDialHandler GetDialHandler
	// GetInfoHandler sets the operation handler for the get info operation
	GetInfoHandler GetInfoHandler
	// GetInstanceHandler sets the operation handler for the get instance operation
	GetInstanceHandler GetInstanceHandler
	// GetInstancesHandler sets the operation handler for the get instances operation
	GetInstancesHandler GetInstancesHandler
	// GetServiceHandler sets the operation handler for the get service operation
	GetServiceHandler GetServiceHandler
	// GetServiceByInstanceIDHandler sets the operation handler for the get service by instance Id operation
	GetServiceByInstanceIDHandler GetServiceByInstanceIDHandler
	// GetServicePlanHandler sets the operation handler for the get service plan operation
	GetServicePlanHandler GetServicePlanHandler
	// GetServicePlansHandler sets the operation handler for the get service plans operation
	GetServicePlansHandler GetServicePlansHandler
	// PingInstanceHandler sets the operation handler for the ping instance operation
	PingInstanceHandler PingInstanceHandler
	// UpdateCatalogHandler sets the operation handler for the update catalog operation
	UpdateCatalogHandler UpdateCatalogHandler
	// UpdateDialHandler sets the operation handler for the update dial operation
	UpdateDialHandler UpdateDialHandler
	// UpdateInstanceHandler sets the operation handler for the update instance operation
	UpdateInstanceHandler UpdateInstanceHandler
	// UpdateServiceHandler sets the operation handler for the update service operation
	UpdateServiceHandler UpdateServiceHandler
	// UpdateServicePlanHandler sets the operation handler for the update service plan operation
	UpdateServicePlanHandler UpdateServicePlanHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup
}

// SetDefaultProduces sets the default produces media type
func (o *UsbMgmtAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *UsbMgmtAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// DefaultProduces returns the default produces media type
func (o *UsbMgmtAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *UsbMgmtAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *UsbMgmtAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *UsbMgmtAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the UsbMgmtAPI
func (o *UsbMgmtAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.AuthorizationAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.CreateDialHandler == nil {
		unregistered = append(unregistered, "CreateDialHandler")
	}

	if o.CreateInstanceHandler == nil {
		unregistered = append(unregistered, "CreateInstanceHandler")
	}

	if o.DeleteDialHandler == nil {
		unregistered = append(unregistered, "DeleteDialHandler")
	}

	if o.DeleteInstanceHandler == nil {
		unregistered = append(unregistered, "DeleteInstanceHandler")
	}

	if o.GetAllDialsHandler == nil {
		unregistered = append(unregistered, "GetAllDialsHandler")
	}

	if o.GetDialHandler == nil {
		unregistered = append(unregistered, "GetDialHandler")
	}

	if o.GetInfoHandler == nil {
		unregistered = append(unregistered, "GetInfoHandler")
	}

	if o.GetInstanceHandler == nil {
		unregistered = append(unregistered, "GetInstanceHandler")
	}

	if o.GetInstancesHandler == nil {
		unregistered = append(unregistered, "GetInstancesHandler")
	}

	if o.GetServiceHandler == nil {
		unregistered = append(unregistered, "GetServiceHandler")
	}

	if o.GetServiceByInstanceIDHandler == nil {
		unregistered = append(unregistered, "GetServiceByInstanceIDHandler")
	}

	if o.GetServicePlanHandler == nil {
		unregistered = append(unregistered, "GetServicePlanHandler")
	}

	if o.GetServicePlansHandler == nil {
		unregistered = append(unregistered, "GetServicePlansHandler")
	}

	if o.PingInstanceHandler == nil {
		unregistered = append(unregistered, "PingInstanceHandler")
	}

	if o.UpdateCatalogHandler == nil {
		unregistered = append(unregistered, "UpdateCatalogHandler")
	}

	if o.UpdateDialHandler == nil {
		unregistered = append(unregistered, "UpdateDialHandler")
	}

	if o.UpdateInstanceHandler == nil {
		unregistered = append(unregistered, "UpdateInstanceHandler")
	}

	if o.UpdateServiceHandler == nil {
		unregistered = append(unregistered, "UpdateServiceHandler")
	}

	if o.UpdateServicePlanHandler == nil {
		unregistered = append(unregistered, "UpdateServicePlanHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *UsbMgmtAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *UsbMgmtAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name, scheme := range schemes {
		switch name {

		case "Authorization":

			result[name] = security.APIKeyAuth(scheme.Name, scheme.In, func(tok string) (interface{}, error) { return o.AuthorizationAuth(tok) })

		}
	}
	return result

}

// ConsumersFor gets the consumers for the specified media types
func (o *UsbMgmtAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *UsbMgmtAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *UsbMgmtAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

func (o *UsbMgmtAPI) initHandlerCache() {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/dials"] = NewCreateDial(o.context, o.CreateDialHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/instances"] = NewCreateInstance(o.context, o.CreateInstanceHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/dials/{dial_id}"] = NewDeleteDial(o.context, o.DeleteDialHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers[strings.ToUpper("DELETE")] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/instances/{instance_id}"] = NewDeleteInstance(o.context, o.DeleteInstanceHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/dials"] = NewGetAllDials(o.context, o.GetAllDialsHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/dials/{dial_id}"] = NewGetDial(o.context, o.GetDialHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/info"] = NewGetInfo(o.context, o.GetInfoHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/instances/{instance_id}"] = NewGetInstance(o.context, o.GetInstanceHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/instances"] = NewGetInstances(o.context, o.GetInstancesHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/services/{service_id}"] = NewGetService(o.context, o.GetServiceHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/services"] = NewGetServiceByInstanceID(o.context, o.GetServiceByInstanceIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/plans/{plan_id}"] = NewGetServicePlan(o.context, o.GetServicePlanHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/plans"] = NewGetServicePlans(o.context, o.GetServicePlansHandler)

	if o.handlers["GET"] == nil {
		o.handlers[strings.ToUpper("GET")] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/instances/{instance_id}/ping"] = NewPingInstance(o.context, o.PingInstanceHandler)

	if o.handlers["POST"] == nil {
		o.handlers[strings.ToUpper("POST")] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/update_catalog"] = NewUpdateCatalog(o.context, o.UpdateCatalogHandler)

	if o.handlers["PUT"] == nil {
		o.handlers[strings.ToUpper("PUT")] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/dials/{dial_id}"] = NewUpdateDial(o.context, o.UpdateDialHandler)

	if o.handlers["PUT"] == nil {
		o.handlers[strings.ToUpper("PUT")] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/instances/{instance_id}"] = NewUpdateInstance(o.context, o.UpdateInstanceHandler)

	if o.handlers["PUT"] == nil {
		o.handlers[strings.ToUpper("PUT")] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/services/{service_id}"] = NewUpdateService(o.context, o.UpdateServiceHandler)

	if o.handlers["PUT"] == nil {
		o.handlers[strings.ToUpper("PUT")] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/plans/{plan_id}"] = NewUpdateServicePlan(o.context, o.UpdateServicePlanHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *UsbMgmtAPI) Serve(builder middleware.Builder) http.Handler {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}

	return o.context.APIHandler(builder)
}
