package genmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*Dial dial

swagger:model dial
*/
type Dial struct {

	/* configuration
	 */
	Configuration interface{} `json:"configuration,omitempty"`

	/* driver instance id

	Required: true
	Max Length: 36
	Min Length: 36
	*/
	DriverInstanceID *string `json:"driver_instance_id"`

	/* id
	 */
	ID string `json:"id,omitempty"`

	/* plan
	 */
	Plan string `json:"plan,omitempty"`
}

// Validate validates this dial
func (m *Dial) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDriverInstanceID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Dial) validateDriverInstanceID(formats strfmt.Registry) error {

	if err := validate.Required("driver_instance_id", "body", m.DriverInstanceID); err != nil {
		return err
	}

	if err := validate.MinLength("driver_instance_id", "body", string(*m.DriverInstanceID), 36); err != nil {
		return err
	}

	if err := validate.MaxLength("driver_instance_id", "body", string(*m.DriverInstanceID), 36); err != nil {
		return err
	}

	return nil
}
