package genmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

/*driver_instance DriverInstance driver instance

swagger:model driver_instance
*/
type DriverInstance struct {

	/* Configuration configuration
	 */
	Configuration interface{} `json:"configuration,omitempty"`

	/* Dials dials
	 */
	Dials []string `json:"dials,omitempty"`

	/* DriverID driver id

	Required: true
	Max Length: 36
	Min Length: 36
	*/
	DriverID string `json:"driver_id,omitempty"`

	/* ID id
	 */
	ID *string `json:"id,omitempty"`

	/* Name name

	Required: true
	*/
	Name string `json:"name,omitempty"`

	/* Service service
	 */
	Service *string `json:"service,omitempty"`

	TargetURL string `json:"target,omitempty"`
}

// Validate validates this driver instance
func (m *DriverInstance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDials(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateDriverID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DriverInstance) validateDials(formats strfmt.Registry) error {

	if swag.IsZero(m.Dials) { // not required
		return nil
	}

	for i := 0; i < len(m.Dials); i++ {

		if err := validate.Required("dials"+"."+strconv.Itoa(i), "body", string(m.Dials[i])); err != nil {
			return err
		}

	}

	return nil
}

func (m *DriverInstance) validateDriverID(formats strfmt.Registry) error {

	if err := validate.Required("driver_id", "body", string(m.DriverID)); err != nil {
		return err
	}

	if err := validate.MinLength("driver_id", "body", string(m.DriverID), 36); err != nil {
		return err
	}

	if err := validate.MaxLength("driver_id", "body", string(m.DriverID), 36); err != nil {
		return err
	}

	return nil
}

func (m *DriverInstance) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}
