package genmodel

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*DriverSchema driver schema

swagger:model driver_schema
*/
type DriverSchema string

// Validate validates this driver schema
func (m DriverSchema) Validate(formats strfmt.Registry) error {
	return nil
}
