package genmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
)

/*
DriverConfig driver config

swagger:model driver_config
*/
type DriverConfig struct {

	/* DriverType driver type
	 */
	DriverType string `json:"driver_type,omitempty"`

	/* ID id

	Required: true
	*/
	ID string `json:"id"`

	/* Name name

	Required: true
	*/
	Name string `json:"name"`

	/* Services services
	 */
	Services []string `json:"services,omitempty"`
}

// Validate validates this driver config
func (m *DriverConfig) Validate(formats strfmt.Registry) error {

	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}

	return nil
}

func (m *DriverConfig) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *DriverConfig) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}
