package genmodel

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*EndpointMetadata endpoint metadata

swagger:model endpointMetadata
*/
type EndpointMetadata struct {

	/* The name of the service to be displayed in graphical clients

	 */
	DisplayName string `json:"displayName,omitempty"`

	/* Link to a documentation page for the service

	 */
	DocumentationURL string `json:"documentationUrl,omitempty"`

	/* The URL to an image

	 */
	ImageURL string `json:"imageUrl,omitempty"`

	/* Long description

	 */
	LongDescription string `json:"longDescription,omitempty"`

	/* The name of the upstream entity providing the actual service

	 */
	ProviderDisplayName string `json:"providerDisplayName,omitempty"`

	/* Link to support information for the service

	 */
	SupportURL string `json:"supportUrl,omitempty"`
}

// Validate validates this endpoint metadata
func (m *EndpointMetadata) Validate(formats strfmt.Registry) error {
	return nil
}
