package genmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*
Error error

swagger:model error
*/
type Error struct {

	/* Code code
	 */
	Code int64 `json:"code,omitempty"`

	/* Messsage messsage
	 */
	Messsage string `json:"messsage,omitempty"`
}
