package genmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
)

/*
Plan plan

swagger:model plan
*/
type Plan struct {

	/* Description description
	 */
	Description string `json:"description,omitempty"`

	/* Free free
	 */
	Free bool `json:"free,omitempty"`

	/* ID id

	Required: true
	*/
	ID string `json:"id"`

	/* Name name

	Required: true
	*/
	Name string `json:"name"`
}

// Validate validates this plan
func (m *Plan) Validate(formats strfmt.Registry) error {

	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}

	return nil
}

func (m *Plan) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *Plan) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}
