package genmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
)

/*plan Plan plan

swagger:model plan
*/
type Plan struct {

	/* Description description
	 */
	Description *string `json:"description,omitempty"`

	/* DialID dial id

	Required: true
	Max Length: 36
	Min Length: 36
	*/
	DialID string `json:"dial_id,omitempty"`

	/* Free free
	 */
	Free *bool `json:"free,omitempty"`

	/* ID id
	 */
	ID *string `json:"id,omitempty"`

	/* Name name

	Required: true
	Max Length: 50
	Min Length: 3
	*/
	Name string `json:"name,omitempty"`
}

// Validate validates this plan
func (m *Plan) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDialID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plan) validateDialID(formats strfmt.Registry) error {

	if err := validate.RequiredString("dial_id", "body", string(m.DialID)); err != nil {
		return err
	}

	if err := validate.MinLength("dial_id", "body", string(m.DialID), 36); err != nil {
		return err
	}

	if err := validate.MaxLength("dial_id", "body", string(m.DialID), 36); err != nil {
		return err
	}

	return nil
}

func (m *Plan) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", string(m.Name), 3); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(m.Name), 50); err != nil {
		return err
	}

	return nil
}
