language: go
sudo: false
go:
- 1.4
- 1.5
install:
- DST=~/gopath/src/github.com/nats-io
- mkdir -p "$DST"
- git clone --depth=1 --quiet https://github.com/nats-io/gnatsd.git "$DST"/gnatsd
- go get -t ./...
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go fmt ./...
- go vet ./...
- go test -i -race ./...
- go test -v -race -p=1 ./...
- GOMAXPROCS=1 go test -v -p=1 -covermode=count -coverprofile=coverage.out ./test
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service travis-ci
