package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/hpcloud/cf-usb/lib/servicemgr/client/connection"
	"github.com/hpcloud/cf-usb/lib/servicemgr/client/workspace"
)

// Default servicemgr HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new servicemgr HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Servicemgr {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http"})
	return New(transport, formats)
}

// New creates a new servicemgr client
func New(transport client.Transport, formats strfmt.Registry) *Servicemgr {
	cli := new(Servicemgr)
	cli.Transport = transport

	cli.Connection = connection.New(transport, formats)

	cli.Workspace = workspace.New(transport, formats)

	return cli
}

// Servicemgr is a client for servicemgr
type Servicemgr struct {
	Connection *connection.Client

	Workspace *workspace.Client

	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Servicemgr) SetTransport(transport client.Transport) {
	c.Transport = transport

	c.Connection.SetTransport(transport)

	c.Workspace.SetTransport(transport)

}
