package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkspaceParams creates a new GetWorkspaceParams object
// with the default values initialized.
func NewGetWorkspaceParams() *GetWorkspaceParams {
	var ()
	return &GetWorkspaceParams{}
}

/*GetWorkspaceParams contains all the parameters to send to the API endpoint
for the get workspace operation typically these are written to a http.Request
*/
type GetWorkspaceParams struct {

	/*WorkspaceID
	  Workspace ID

	*/
	WorkspaceID string
}

// WithWorkspaceID adds the workspaceId to the get workspace params
func (o *GetWorkspaceParams) WithWorkspaceID(WorkspaceID string) *GetWorkspaceParams {
	o.WorkspaceID = WorkspaceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param workspace_id
	if err := r.SetPathParam("workspace_id", o.WorkspaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
