#!/bin/sh

OSES="linux darwin"

set -o errexit

. make/include/colors.sh
#. make/include/versioning.sh
APP_VERSION=1.3.0

echo "${OK_COLOR}==> Building ${ERROR_COLOR}"

for OS in ${OSES}; do \
		 env GOOS=${OS} GOARCH=amd64 go build -o build/${OS}-amd64/usb/usb \
		 -ldflags="-X main.version=${APP_VERSION}" \
		 ./cmd/usb/  
done

echo "${NO_COLOR}\c"
