#!/bin/sh

OSES="linux darwin"

set -o errexit

. make/include/colors.sh
. make/include/versioning.sh


printf "${OK_COLOR}==> Disting all${NO_COLOR}\n"
for OS in ${OSES}; do \
	cd build/${OS}-amd64/ 1> /dev/null; tar czf ../../cf-usb-${APP_VERSION}-${OS}-amd64.tgz ./; cd - 1> /dev/null; \
done; 
