#!/bin/sh

set -o errexit

. make/include/colors.sh

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

printf "${OK_COLOR}==> Generating CSM client ${NO_COLOR}\n"

rm -rf ${GIT_ROOT}/lib/csm/models/ ${GIT_ROOT}/lib/csm/client/

${GIT_ROOT}/.tools/swagger generate client \
	-f ${GOPATH}/src/github.com/SUSE/cf-usb-sidecar/docs/swagger-spec/api.yml \
	-t ${GIT_ROOT}/lib/csm
	
printf "${OK_COLOR}==> Generating management API ${NO_COLOR}\n"
rm -rf ${GIT_ROOT}/lib/operations ${GIT_ROOT}/lib/genmodel

${GIT_ROOT}/.tools/swagger generate server -f ${GIT_ROOT}/swagger-spec/management-api.json -m genmodel -s "mgmt" -A usb-mgmt -t ${GIT_ROOT}/lib --exclude-main
rm lib/mgmt/server.go

printf "${OK_COLOR}==> Generating broker API ${NO_COLOR}\n"
${GIT_ROOT}/.tools/swagger generate server -f ${GIT_ROOT}/swagger-spec/broker-api.json -m brokermodel -s "broker" -A broker -t ${GIT_ROOT}/lib --exclude-main
rm lib/broker/server.go
