#!/bin/sh

set -o errexit

. make/include/colors.sh

printf "%b==> Linting%b\n" "${OK_COLOR}" "${ERROR_COLOR}"

ISSUES=$(mktemp)

trap "cat ${ISSUES} ; rm -f ${ISSUES}" EXIT

go list -f '{{ .Dir }}' ./... | grep -v csm/client |  grep -v operations | grep -v /vendor/ | grep -v mocks | grep -v csmfakes | while read DIR; do
    golint "${DIR}" >> "${ISSUES}"
done

printf "%b" "${NO_COLOR}"

test ! -s "${ISSUES}"
