#!/bin/sh

OSES="linux darwin"

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

set -o errexit

. make/include/colors.sh

printf "${OK_COLOR}==> Installing tools${NO_COLOR}\n"
#Great tools to have, and used in the build file
go get -u golang.org/x/tools/cmd/goimports
go get -u golang.org/x/tools/cmd/cover
go get -u github.com/golang/lint/golint
go get github.com/AlekSi/gocov-xml

	
#Tools for the project
go get -u github.com/axw/gocov/gocov
	
#go get github.com/hashicorp/consul

echo "Fetching go-swagger"

swagger_file=${GIT_ROOT}/.tools/swagger

if [ -f $swagger_file ] ; then
  rm $swagger_file
fi

export GOPATH=${GIT_ROOT}/.temp

go get -u github.com/go-swagger/go-swagger/cmd/swagger
cd  ${GIT_ROOT}/.temp/src/github.com/go-swagger/go-swagger
git reset --hard 0.5.9 
go build -o ${GIT_ROOT}/.tools/swagger ${GIT_ROOT}/.temp/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go
rm -rf ${GIT_ROOT}/.temp
