#!/bin/sh

set -o errexit

. make/include/colors.sh

printf "${OK_COLOR}==> Vetting${ERROR_COLOR}\n"


go list -f '{{ .Dir }}' ./... | grep -v /vendor/  | tr ' ' '\n' | xargs -I '{p}' -n1 go tool vet -composites=false {p} | sed "s/^/Failed: /"

printf "${NO_COLOR}"
