swagger: '2.0'
info:
  version: 0.0.1
  title: USB management api
paths:
  /info:
    get:
      description: |
        Gets information about the USB.
      responses:
        200:
          description: Successful response
          schema:
            title: USB Indo
            type: object
            properties:
              version:
                type: string
  /drivers:
    get:
      description: |
        Gets information about the available `driver`
      responses:
        200:
          description: Sucessfull response
          schema:
            title: ArrayOfDrivers
            type: array
            items:
              type: string
          
  /driver_config:
    get:
      description: |
        Gets all driver configurations
      responses:
        200:
          description: OK
          schema:
            title: ArrayOfDriverConfigs
            type: array
            items:
              $ref: '#/definitions/driver_config'
    post:
      description: | 
        Create a new driver
      parameters:
        - name: driver_config
          in: body
          description: Add driver_config
          required: true
          schema:
            $ref: '#/definitions/driver_config'
      responses:
        201:
          description: Sucessfull response
    
  '/driver_config/{driver_config_id}':
    parameters:
      - name: driver_config_id
        in: path
        description: ID of the service
        required: true
        type: string
    get:
      description: |
        Gets a `driver` configuration
      responses:
        200:
          description: Sucessfull response
          schema:
            $ref: '#/definitions/driver_config'
    put:
      description: Updates the driver config with the id **driver_config_id**
      parameters:
        - name: driver_config
          in: body
          description: Add driver_config
          required: true
          schema:
            $ref: '#/definitions/driver_config'
      responses:
        201:
          description: Sucessfull response
    
    delete:
      description: |
        Deletes a `driver` configuration
      responses:
        204:
          description: Sucessfull response
          
  /services:
    get:
      description: |
        Gets the existing `service`
      responses:
        200:
          description: Sucessfull response
          schema:
            title: ArrayOfServices
            type: array
            items:
              title: Services
              type: array
              items:
                $ref: '#/definitions/service'
    post:
      description: | 
        Create a new `service` definition 
      parameters:
        - name: service
          in: body
          description: Add service definition
          required: true
          schema:
            $ref: '#/definitions/service'
      responses:
        201:
          description: Sucessfull response
          
  '/services/{serviceID}':
    parameters:
      - name: serviceID
        in: path
        description: ID of the service
        required: true
        type: string
    get:
      description: Gets the service with the id **serviceID** 
      responses:
        200:
          description: Sucessfull response
          schema:
            $ref: '#/definitions/service'
    put:
      description: Updates the service with the id **serviceID**
      parameters:
        - name: service
          in: body
          description: Update service
          required: true
          schema:
            $ref: '#/definitions/service'
      responses:
        201:
          description: Sucessfull response
    delete:
      description: |
        Deletes a `service`
      responses:
        204:
          description: Sucessfull response
          
  '/services/{serviceID}/plans':
    parameters:
      - name: serviceID
        in: path
        description: ID of the service
        required: true
        type: string
    get:
      description: Gets the `plans` for the **serviceID** 
      responses:
        200:
          description: Sucessfull response
          schema:
            type: array
            items:
              $ref: '#/definitions/plan'
            
    post:
      description: Create a plan for the **serviceID**
      responses:
        201:
          description: Sucessfull response
      parameters:
        - name: plan
          in: body
          description: Add plan for the **serviceID**
          required: true
          schema:
            $ref: '#/definitions/plan'
          
  '/services/{serviceID}/plans/{planID}':
    parameters:
      - name: serviceID
        in: path
        description: ID of the service
        required: true
        type: string
      - name: planID
        in: path
        description: ID of the plan
        required: true
        type: string
    get:
      description: Gets the `plan` with the **planID** for the *serviceID*
      responses:
        200:
          description: Sucessfull response
          schema:
            $ref: '#/definitions/plan'
    put:
      description: Updates the plan with the id **planID** for the service id **serviceID**
      parameters:
        - name: plan
          in: body
          description: Update plan
          required: true
          schema:
            $ref: '#/definitions/plan'
      responses:
        201:
          description: Sucessfull response
    delete:
      description: Delets the `plan` with the **planID** for the **serviceID** 
      responses:
        204:
          description: Sucessfull response
    
        
definitions:
  service:
    type: object
    properties:
      id:
        type: string
      bindable:
        type: boolean
      name:
        type: string
      description:
        type: string
      tags:
        type: array
        items:
          title: description
          type: string
      metadata:
        type: object
      driver_type:
        type: string
      plans:
        type: array
        items:
          $ref: '#/definitions/plan'
  plan:
    type: object
    properties:
      name:
        type: string
      id:
        type: string
      description:
        type: string
      free:
        type: boolean
  driver_config:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      driver_type:
        type: string
      services:
        type: array
        items: 
          type: string