package brokermodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Empty Expected empty response could be {}

swagger:model Empty
*/
type Empty struct {

	/* fake
	 */
	Fake string `json:"fake,omitempty"`
}

// Validate validates this empty
func (m *Empty) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
