package brokermodel

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Empty Expected empty response could be {}

swagger:model Empty
*/
type Empty string

// Validate validates this empty
func (m Empty) Validate(formats strfmt.Registry) error {
	return nil
}
