package brokermodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*LastOperation Last operation response.

swagger:model LastOperation
*/
type LastOperation struct {

	/* description
	 */
	Description string `json:"description,omitempty"`

	/* state
	 */
	State string `json:"state,omitempty"`
}

// Validate validates this last operation
func (m *LastOperation) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
