package brokermodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*Plan A plan for the service

swagger:model Plan
*/
type Plan struct {

	/* A short description of the service that will appear in the catalog.
	 */
	Description string `json:"description,omitempty"`

	/* This field allows the plan to be limited by the non_basic_services_allowed field in a Cloud Foundry Quota, [see Quota Plans](http://docs.cloudfoundry.org/running/managing-cf/quota-plans.html).
	 */
	Free bool `json:"free,omitempty"`

	/* An identifier used to correlate this plan in future requests to the catalog. This must be unique within Cloud Foundry, using a GUID is recommended.
	 */
	ID string `json:"id,omitempty"`

	/* A list of metadata for a service plan. For more information, [see Service Metadata](https://docs.cloudfoundry.org/services/catalog-metadata.html).
	 */
	Metadata interface{} `json:"metadata,omitempty"`

	/* The CLI-friendly name of the plan that will appear in the catalog. All lowercase, no spaces.
	 */
	Name string `json:"name,omitempty"`
}

// Validate validates this plan
func (m *Plan) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
